-- usage_daily backfill generated 2026-06-04T17:15:56.948Z
-- 121 day-user rows from 2660 activity events (skipped 0 same-day events)
BEGIN;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-09', '+14243937267', 6, 6, 6, 6, 0, 386, 2894, 47087, 394128, 0.659470, 124)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-09', '+16262300167', 27, 24, 26, 26, 0, 412, 8473, 303757, 946603, 6.999903, 854)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-09', '+19254357161', 15, 15, 15, 15, 0, 62, 6403, 160061, 461864, 1.425692, 224)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-10', '+19254357161', 2, 2, 2, 2, 0, 7, 925, 40185, 48121, 0.298377, 27)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-11', '+16262300167', 19, 16, 19, 16, 3, 51, 2452, 180063, 211914, 1.003239, 138)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-12', '+16262300167', 19, 19, 19, 19, 0, 77, 8561, 297334, 731852, 1.621681, 391)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-13', '+16262300167', 3, 1, 3, 1, 2, 3, 10, 11310, 8567, 0.045142, 9)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-14', '+14243937267', 3, 3, 3, 3, 0, 9, 200, 27621, 34603, 0.116987, 15)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-14', '+16262300167', 18, 18, 18, 18, 0, 859, 3710, 309870, 538848, 1.702681, 199)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-15', '+14243937267', 5, 5, 9, 9, 0, 38, 1802, 127376, 241381, 0.577218, 69)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-15', '+16262300167', 13, 13, 13, 13, 0, 44, 3489, 263705, 380219, 1.361309, 172)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-16', '+14243937267', 2, 2, 2, 2, 0, 6, 47, 29439, 12594, 0.114897, 10)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-16', '+16262300167', 10, 10, 10, 10, 0, 37, 4952, 131348, 276872, 0.702427, 149)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-17', '+16262300167', 4, 4, 4, 4, 0, 14, 1416, 113310, 107866, 0.549584, 63)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-18', '+16262300167', 2, 2, 2, 2, 0, 7, 1130, 35820, 33233, 0.527972, 110)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-19', '+16267860274', 9, 9, 9, 9, 0, 60, 14823, 199308, 1158931, 1.845253, 463)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-20', '+15625386577', 2, 2, 2, 2, 0, 14, 741, 22333, 107431, 0.127135, 34)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-20', '+16262300167', 3, 3, 3, 3, 0, 12, 1151, 42819, 93804, 0.588635, 137)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-21', '+16262300167', 7, 7, 7, 7, 0, 24, 2826, 116388, 185991, 0.822982, 164)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-22', '+16262300167', 1, 1, 1, 1, 0, 3, 20, 29034, 6212, 0.111050, 5)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-22', '+16267860274', 9, 9, 9, 9, 0, 38, 2259, 109654, 356117, 0.808092, 153)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-23', '+14243937267', 32, 29, 29, 29, 0, 143, 9191, 524769, 1769035, 2.667677, 345)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-23', '+16262300167', 8, 8, 8, 8, 0, 28, 3216, 223669, 196696, 0.946092, 113)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-24', '+14243937267', 1, 1, 1, 1, 0, 4, 300, 30330, 41732, 0.158393, 14)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-24', '+16262300167', 1, 1, 1, 1, 0, 4, 502, 42856, 53780, 0.624521, 99)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-25', '+16262300167', 1, 1, 1, 1, 0, 4, 591, 46765, 56560, 0.660007, 122)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-25', '+254769235202', 1, 1, 1, 1, 0, 3, 273, 14470, 6212, 0.060230, 9)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-26', '+14243937267', 31, 30, 30, 30, 0, 200, 27833, 858727, 3505903, 4.690092, 845)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-26', '+16262300167', 4, 4, 4, 4, 0, 23, 1635, 46097, 148363, 0.265583, 78)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-26', '+16267860274', 2, 2, 2, 2, 0, 9, 1288, 50204, 125325, 0.338790, 59)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-27', '+14243937267', 16, 16, 16, 16, 0, 62, 5647, 442991, 588023, 1.922514, 251)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-28', '+16262300167', 4, 4, 4, 4, 0, 14, 1120, 74855, 100476, 0.388831, 62)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-29', '+14243937267', 3, 3, 3, 3, 0, 9, 1388, 129405, 33324, 0.516113, 45)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-29', '+16262300167', 1, 1, 1, 1, 0, 2105, 1276, 28037, 79582, 0.335151, 59)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-30', '+16262300167', 1, 1, 1, 1, 0, 3, 343, 7126, 11212, 0.035240, 11)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-31', '+14243937267', 8, 8, 8, 8, 0, 1073, 39686, 309191, 2522323, 2.884473, 1210)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-03-31', '+254769235202', 5, 5, 5, 5, 0, 15, 1046, 38153, 56060, 0.175627, 43)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-01', '+14243937267', 11, 10, 11, 10, 0, 95, 34177, 1165471, 6587094, 7.375050, 1029)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-01', '+16262300167', 5, 5, 5, 5, 0, 16, 1363, 57998, 79213, 0.756813, 177)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-01', '+254769235202', 3, 3, 3, 3, 0, 9, 1924, 34646, 33636, 0.168900, 62)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-02', '+16262300167', 2, 2, 2, 2, 0, 6, 27, 34869, 22010, 0.137785, 11)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-05', '+14243937267', 20, 19, 20, 19, 1, 125, 73882, 1202138, 4696390, 7.307979, 1550)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-08', '+14243937267', 17, 17, 17, 17, 0, 2007, 61043, 1303477, 5536489, 7.840088, 1384)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-09', '+14243937267', 5, 5, 5, 5, 0, 33, 11715, 632843, 2346114, 3.295490, 304)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-10', '+14243937267', 4, 4, 4, 4, 0, 14, 2480, 553709, 319295, 2.209439, 122)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-11', '+14243937267', 2, 2, 2, 2, 0, 10, 2289, 295563, 309720, 1.235642, 84)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-12', '+14243937267', 9, 9, 9, 9, 0, 66, 17618, 532650, 1626118, 2.749741, 376)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-12', '+61499403008', 12, 12, 12, 12, 0, 68, 37547, 471652, 1421833, 2.878800, 738)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-13', '+14243937267', 14, 14, 14, 14, 0, 112, 31232, 289523, 1316229, 1.949396, 558)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-14', '+14243937267', 13, 13, 13, 13, 0, 3185, 15035, 713462, 1116174, 3.449449, 408)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-15', '+14243937267', 25, 25, 25, 25, 0, 3240, 52987, 2060480, 4219427, 10.294371, 1271)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-15', '+918979484010', 3, 3, 3, 3, 0, 22, 2612, 32265, 256286, 0.237126, 168)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-16', '+14243937267', 3, 3, 3, 3, 0, 15, 3652, 351047, 719383, 1.646894, 112)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-16', '+16262300167', 3, 3, 3, 3, 0, 14, 1126, 34745, 65903, 0.166997, 38)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-16', '+918979484010', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0.000000, 600)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-17', '+16262300167', 1, 1, 1, 1, 0, 7, 605, 25837, 38008, 0.117387, 18)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-17', '+918979484010', 10, 10, 10, 10, 0, 149, 89814, 1054008, 11893921, 9.020481, 1705)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-19', '+14243937267', 9, 9, 9, 9, 0, 215, 21812, 978201, 3342857, 5.345261, 668)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-19', '+918979484010', 3, 3, 3, 3, 0, 23, 4960, 356383, 1727210, 1.929068, 275)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-20', '+14243937267', 1, 1, 1, 1, 0, 3, 17, 17607, 0, 0.066290, 6)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-20', '+16264640195', 12, 10, 11, 10, 0, 89, 68499, 811853, 6577485, 6.045446, 1911)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-20', '+918979484010', 2, 2, 2, 2, 0, 47, 31594, 365243, 4358843, 3.316639, 654)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-21', '+14243937267', 3, 3, 3, 3, 0, 905, 4274, 57851, 308129, 0.516276, 154)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-21', '+16264640195', 22, 23, 23, 23, 0, 259, 89583, 2402357, 17690939, 15.820290, 2078)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-21', '+918979484010', 8, 8, 8, 8, 0, 125, 64912, 860093, 8220070, 7.468989, 1680)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-22', '+14243937267', 1, 1, 1, 1, 0, 4, 1239, 33494, 31288, 0.219049, 51)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-22', '+918979484010', 11, 10, 11, 10, 0, 158, 90732, 1338949, 13205322, 10.704203, 2747)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-23', '+14243937267', 7, 7, 7, 7, 0, 34, 6485, 262874, 558430, 1.250684, 225)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-23', '+918979484010', 3, 3, 3, 3, 0, 46, 29337, 392951, 4141039, 3.156071, 547)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-24', '+61499403008', 4, 4, 4, 4, 0, 15, 4661, 67993, 75626, 0.347622, 124)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-25', '+16262300167', 1, 1, 1, 1, 0, 3, 21, 16807, 0, 0.063350, 5)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-25', '+254769235202', 5, 5, 5, 5, 0, 15, 1193, 50296, 33984, 0.216745, 60)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-26', '+14243937267', 1, 1, 1, 1, 0, 7, 2987, 62267, 235637, 0.349018, 178)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-27', '+14243937267', 7, 7, 7, 7, 0, 50, 30971, 651020, 2568884, 3.676705, 674)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-27', '+16262300167', 16, 15, 15, 15, 0, 233, 48465, 971921, 8465620, 7.009622, 1202)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-27', '+61499403008', 16, 16, 16, 16, 0, 61, 12601, 649917, 735155, 2.995353, 468)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-27', '+918979484010', 1, 1, 1, 1, 0, 11, 1736, 177720, 307798, 0.968352, 207)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-28', '+14243937267', 1, 1, 1, 1, 0, 5, 743, 134126, 266767, 0.594163, 51)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-28', '+16262300167', 2, 2, 2, 2, 0, 6, 745, 307348, 8496, 1.166297, 35)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-29', '+14243937267', 6, 5, 6, 5, 0, 26, 4857, 692203, 1305499, 3.060344, 809)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-29', '+16262300167', 4, 4, 4, 4, 0, 48, 23059, 386415, 1458450, 15.590725, 469)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-30', '+14243937267', 16, 13, 14, 13, 0, 25696, 31239, 871805, 1976788, 4.407978, 1297)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-30', '+16262300167', 3, 3, 3, 3, 0, 18, 486, 218406, 23618, 4.167260, 29)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-30', '+16264640195', 57, 53, 57, 53, 0, 24640, 454477, 4635899, 50851646, 46.170761, 12880)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-04-30', '+918979484010', 1, 1, 1, 1, 0, 19, 10153, 51490, 804104, 0.586671, 229)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-01', '+14243937267', 9, 9, 9, 9, 0, 59, 19790, 338624, 991769, 2.155606, 579)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-02', '+14243937267', 2, 2, 2, 2, 0, 19, 14640, 156029, 759853, 1.611215, 497)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-03', '+14243937267', 2, 2, 2, 2, 0, 15, 11860, 199461, 759964, 1.153913, 259)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-04', '+16262300167', 4, 4, 4, 4, 0, 40, 29830, 173947, 816922, 1.344948, 434)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-05', '+14243937267', 5, 5, 5, 5, 0, 29, 20605, 638123, 1612924, 3.298196, 411)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-05', '+16262300167', 3, 3, 3, 3, 0, 12, 11701, 307481, 304709, 1.420017, 210)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-06', '+14243937267', 2, 2, 2, 2, 0, 781, 2810, 313578, 943219, 1.589825, 96)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-07', '+918979484010', 1, 1, 1, 1, 0, 22, 5404, 31561, 464027, 0.470241, 192)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-08', '+918979484010', 3, 3, 3, 3, 0, 47, 17091, 159820, 2071508, 1.785529, 608)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-08', '+919737373872', 3, 3, 3, 3, 0, 10, 1326, 42926, 23701, 0.432314, 91)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-09', '+61499403008', 16, 16, 16, 16, 0, 58, 6191, 423963, 399176, 1.802653, 248)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-10', '+61475052502', 1, 1, 1, 1, 0, 3, 67, 17670, 0, 0.067277, 7)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-11', '+14243937267', 2, 2, 2, 2, 0, 15, 5471, 183290, 371717, 1.558126, 529)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-11', '+353892069336', 16, 13, 16, 13, 0, 56, 29134, 557605, 839197, 2.779956, 2337)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-11', '+918979484010', 3, 3, 3, 3, 0, 54, 17537, 273925, 4347556, 2.594703, 482)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-12', '+14243937267', 1, 1, 1, 1, 0, 3, 456, 42067, 0, 0.164600, 17)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-12', '+353892069336', 4, 4, 4, 4, 0, 26, 24870, 209666, 307012, 1.434373, 510)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-13', '+14243937267', 5, 5, 5, 5, 0, 67, 51773, 484002, 3676368, 3.694714, 992)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-14', '+14243937267', 6, 6, 6, 6, 0, 36, 34658, 626466, 1630918, 3.524897, 663)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-16', '+14243937267', 6, 5, 6, 5, 0, 60, 31615, 522603, 4455050, 3.902633, 1310)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-19', '+353892069336', 4, 3, 3, 3, 0, 27, 8349, 579084, 904647, 2.568275, 267)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-20', '+353892069336', 15, 15, 16, 15, 0, 74, 66135, 1488361, 1689968, 8.384161, 2518)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-21', '+353892069336', 19, 16, 18, 16, 0, 87, 103415, 1497043, 2006362, 8.622069, 3531)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-22', '+353892069336', 14, 14, 15, 14, 0, 83, 87793, 1594171, 4066521, 9.234880, 2444)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-23', '+14243937267', 10, 10, 10, 10, 0, 1668, 21242, 679922, 1979810, 3.730114, 517)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-23', '+353892069336', 5, 4, 5, 4, 0, 27, 19766, 462445, 808223, 3.991695, 1652)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-24', '+14243937267', 20, 17, 19, 17, 0, 131, 99936, 1071082, 4219589, 7.112743, 2921)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-24', '+16262300167', 1, 1, 1, 1, 0, 3, 279, 9902, 8496, 0.043875, 10)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-25', '+14243937267', 11, 12, 12, 12, 0, 102, 94201, 1758610, 3506048, 9.719034, 1815)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-25', '+353892069336', 1, 1, 1, 1, 0, 4, 873, 19816, 18024, 0.482539, 101)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-26', '+353892069336', 1, 1, 1, 1, 0, 4, 783, 22277, 19570, 0.339692, 68)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-28', '+14243937267', 1, 1, 1, 1, 0, 6, 4375, 152630, 148661, 0.682604, 88)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-05-31', '+353892069336', 5, 3, 5, 3, 0, 11, 5563, 70661, 99831, 1.023478, 1647)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-06-02', '+353892069336', 9, 4, 9, 4, 0, 23, 9453, 218696, 682594, 1.641699, 3299)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-06-03', '+14243937267', 3, 3, 3, 3, 0, 10, 4249, 327572, 176456, 1.998512, 182)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
INSERT INTO usage_daily (date, phone, messages_in, messages_out, tasks, completed_tasks, failed_tasks, input_tokens, output_tokens, cache_creation_tokens, cache_read_tokens, cost_usd, duration_secs)
VALUES ('2026-06-03', '+353892069336', 6, 5, 6, 5, 0, 22, 13764, 475873, 667641, 3.208320, 1382)
ON CONFLICT (date, phone) DO UPDATE SET messages_in = EXCLUDED.messages_in, messages_out = EXCLUDED.messages_out, tasks = EXCLUDED.tasks, completed_tasks = EXCLUDED.completed_tasks, failed_tasks = EXCLUDED.failed_tasks, input_tokens = EXCLUDED.input_tokens, output_tokens = EXCLUDED.output_tokens, cache_creation_tokens = EXCLUDED.cache_creation_tokens, cache_read_tokens = EXCLUDED.cache_read_tokens, cost_usd = EXCLUDED.cost_usd, duration_secs = EXCLUDED.duration_secs;
COMMIT;
