export interface CountryCode {
  code: string;
  dial: string;
  flag: string;
}

export const countryCodes: CountryCode[] = [
  { code: "US", dial: "+1", flag: "🇺🇸" },
  { code: "CA", dial: "+1", flag: "🇨🇦" },
  { code: "GB", dial: "+44", flag: "🇬🇧" },
  { code: "IN", dial: "+91", flag: "🇮🇳" },
  { code: "AU", dial: "+61", flag: "🇦🇺" },
  { code: "DE", dial: "+49", flag: "🇩🇪" },
  { code: "FR", dial: "+33", flag: "🇫🇷" },
  { code: "BR", dial: "+55", flag: "🇧🇷" },
  { code: "MX", dial: "+52", flag: "🇲🇽" },
  { code: "JP", dial: "+81", flag: "🇯🇵" },
  { code: "KR", dial: "+82", flag: "🇰🇷" },
  { code: "CN", dial: "+86", flag: "🇨🇳" },
  { code: "IT", dial: "+39", flag: "🇮🇹" },
  { code: "ES", dial: "+34", flag: "🇪🇸" },
  { code: "NL", dial: "+31", flag: "🇳🇱" },
  { code: "SE", dial: "+46", flag: "🇸🇪" },
  { code: "NO", dial: "+47", flag: "🇳🇴" },
  { code: "DK", dial: "+45", flag: "🇩🇰" },
  { code: "FI", dial: "+358", flag: "🇫🇮" },
  { code: "CH", dial: "+41", flag: "🇨🇭" },
  { code: "AT", dial: "+43", flag: "🇦🇹" },
  { code: "BE", dial: "+32", flag: "🇧🇪" },
  { code: "PT", dial: "+351", flag: "🇵🇹" },
  { code: "IE", dial: "+353", flag: "🇮🇪" },
  { code: "NZ", dial: "+64", flag: "🇳🇿" },
  { code: "SG", dial: "+65", flag: "🇸🇬" },
  { code: "HK", dial: "+852", flag: "🇭🇰" },
  { code: "TW", dial: "+886", flag: "🇹🇼" },
  { code: "IL", dial: "+972", flag: "🇮🇱" },
  { code: "AE", dial: "+971", flag: "🇦🇪" },
  { code: "SA", dial: "+966", flag: "🇸🇦" },
  { code: "ZA", dial: "+27", flag: "🇿🇦" },
  { code: "NG", dial: "+234", flag: "🇳🇬" },
  { code: "KE", dial: "+254", flag: "🇰🇪" },
  { code: "EG", dial: "+20", flag: "🇪🇬" },
  { code: "PK", dial: "+92", flag: "🇵🇰" },
  { code: "BD", dial: "+880", flag: "🇧🇩" },
  { code: "PH", dial: "+63", flag: "🇵🇭" },
  { code: "ID", dial: "+62", flag: "🇮🇩" },
  { code: "MY", dial: "+60", flag: "🇲🇾" },
  { code: "TH", dial: "+66", flag: "🇹🇭" },
  { code: "VN", dial: "+84", flag: "🇻🇳" },
  { code: "CO", dial: "+57", flag: "🇨🇴" },
  { code: "AR", dial: "+54", flag: "🇦🇷" },
  { code: "CL", dial: "+56", flag: "🇨🇱" },
  { code: "PE", dial: "+51", flag: "🇵🇪" },
  { code: "PL", dial: "+48", flag: "🇵🇱" },
  { code: "CZ", dial: "+420", flag: "🇨🇿" },
  { code: "RO", dial: "+40", flag: "🇷🇴" },
  { code: "HU", dial: "+36", flag: "🇭🇺" },
  { code: "GR", dial: "+30", flag: "🇬🇷" },
  { code: "TR", dial: "+90", flag: "🇹🇷" },
  { code: "RU", dial: "+7", flag: "🇷🇺" },
  { code: "UA", dial: "+380", flag: "🇺🇦" },
];
